#!/usr/bin/env zsh
# ~/.zshrc: executed by zsh(1) for non-login shells.

# If not running interactively, don't do anything
case $- in
    *i*) ;;
    *) return;;
esac

# Initialize Prezto.
if [[ -s "${ZDOTDIR}/.zprezto/init.zsh" ]]; then
    source "${ZDOTDIR}/.zprezto/init.zsh"
fi

[[ $EMACS = t ]] && unsetopt zle

# The following lines were added by compinstall
zstyle ':completion:*' completer _complete _ignored _approximate
zstyle ':completion:*' completions 1
zstyle ':completion:*' expand prefix suffix
zstyle ':completion:*' glob 0
zstyle ':completion:*' ignore-parents parent
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-suffixes true
zstyle ':completion:*' matcher-list 'm:{[:lower:]}={[:upper:]}' 'm:{[:lower:]}={[:upper:]}'
zstyle ':completion:*' max-errors 3 numeric
zstyle ':completion:*' original true
zstyle ':completion:*' squeeze-slashes true
zstyle ':completion:*' substitute 1
zstyle ':completion:*' insert-unambiguous true
zstyle ':completion:*' insert true
zstyle ':completion:*' insert-tab false
zstyle :compinstall filename '/home/xaldew/.zsh/.zshrc'


autoload -Uz compinit complist
compinit

# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory autocd extendedglob nomatch notify histignorealldups
setopt nocdablevars
unsetopt beep
# End of lines configured by zsh-newuser-install

autoload -U colors && colors

autoload -U select-word-style
select-word-style bash

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# Source common definitions and utilities.
if [ -f "$dotfiles_dir/configs/common.sh" ]; then
    . "$dotfiles_dir/configs/common.sh"
fi

# Set the terminal to ignore filename completion for more suffixes.
export FIGNORE="$FIGNORE:.svn:.o:.~:\#*\#:.pyc::.pyo"


# Add useful bash specific shell-functions.
source_if $dotfiles_dir/scripts/setup_terminal_colors.sh
source_if $dotfiles_dir/scripts/prompt.sh
source_if $dotfiles_dir/scripts/get_distribution.sh
source_if $dotfiles_dir/scripts/yank_readline.sh
source_if $local_prefix_dir/bin/bashmarks.sh


# Add Meta-h to backward-kill-word.
bindkey -M emacs '^[h' backward-kill-word

# Enter accepts the menu entry and inserts the command.
zmodload zsh/complist

# Remove zprezto rm alias.
alias rm=rm
