# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
    *) return;;
esac

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar 2> /dev/null

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"


# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# Enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
    if [ -f /usr/share/bash-completion/bash_completion ]; then
	. /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]; then
	. /etc/bash_completion
    fi
fi


#################################################################

# Set XDG_CONFIG_HOME variable if not set.
if [ -n "$XDG_CONFIG_HOME" -a -d "$HOME/.config" ]; then
    export XDG_CONFIG_HOME=$HOME/.config
fi

# Set the terminal to ignore filename completion for more suffixes.
export FIGNORE=$FIGNORE:svn:.o:.~:\#*\#:.pyc:.pyo


# Setup emacs as the default editor.
if [ "${EDITOR#*emacs}" = "${EDITOR}" ]; then
    export EDITOR=nx-emacs-client
fi
if [ "${VISUAL#*emacs}" = "${VISUAL}" ]; then
    export VISUAL=graphical-emacs-client
fi


# Change bash-history settings.
HISTSIZE=1000
HISTFILESIZE=2000

# Append to the history file; don't overwrite it.
shopt -s histappend

# Avoid duplicates and erase if found.
export HISTCONTROL=ignoredups:erasedups

# Add useful bash specific shell-functions.
source_if $dotfiles_dir/scripts/setup_terminal_colors.sh
source_if $dotfiles_dir/scripts/prompt.sh
source_if $dotfiles_dir/scripts/get_distribution.sh
source_if $dotfiles_dir/scripts/yank_readline.sh
source_if $local_prefix_dir/bin/bashmarks.sh
source_if $local_prefix_dir/bin/git-completion.bash


# Colors for less and man pages.
export LESS="-r"
export LESSOPEN="| pygmentize -g -f terminal256 -O full,style=tango %s"
export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking
export LESS_TERMCAP_md=$'\E[01;38;5;74m'  # begin bold
export LESS_TERMCAP_me=$'\E[0m'           # end mode
export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
export LESS_TERMCAP_so=$'\E[38;5;246m'    # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\E[0m'           # end underline
export LESS_TERMCAP_us=$'\E[04;38;5;146m' # begin underline

# Add extra man-page directories.
export MANPATH=$local_prefix_dir/share/man:$MANPATH

# Add GNU global tags configuration.
export GTAGSCONF="${local_prefix_dir}/share/gtags/gtags.conf"
export GTAGSLABEL=pygments
