#!/usr/bin/env bash

if [ "$OSTYPE" = "cygwin" ]; then
    export SHELLOPTS
    set -o igncr;
    export CHERE_INVOKING=1
    function sudo ()
    {
        cygstart --action=runas $@
    }

    mkdir --parents "$HOME/.config"

    if [ -z "$SSH_AUTH_SOCK" ]; then
        eval $(ssh-agent) > /dev/null
    fi

fi
if [ -f ~/.profile ]; then . ~/.profile; fi
