# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"


# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# Add 256 colour support for the xterm emulators.
export TERM='xterm-256color'

#################################################################

# Set XDG_CONFIG_HOME variable if not set.
if [ -n "$XDG_CONFIG_HOME" -a -d "$HOME/.config" ]; then
    export XDG_CONFIG_HOME=$HOME/.config
fi

# Set the terminal to ignore filename completion for more suffixes.
export FIGNORE=$FIGNORE:svn:.o:.~:\#*\#:.pyc:.pyo

# Add default grep options
export GREP_OPTIONS="--exclude-dir={.svn,.git,.repo}"

# Setup emacs as the default editor.
if [[ ! $EDITOR =~ .*emacs.* ]]; then
   export EDITOR="emacs"
fi

# Change bash-history settings.
HISTSIZE=1000
HISTFILESIZE=2000

# Append to the history file; don't overwrite it.
shopt -s histappend

# Avoid duplicates and erase if found.
export HISTCONTROL=ignoredups:erasedups

# Add Meta-h to backward-kill-word.
bind '"\eh": backward-kill-word'

# Add useful bash specific shell-functions.
source $DOTFILES_DIR/scripts/prompt.sh
source $DOTFILES_DIR/scripts/bashmarks.sh
source $DOTFILES_DIR/scripts/get_distribution.sh

# Colors for less and man pages.
export LESS="-r"
export LESSOPEN="| pygmentize -g -f terminal256 -O full,style=tango %s"
export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking
export LESS_TERMCAP_md=$'\E[01;38;5;74m'  # begin bold
export LESS_TERMCAP_me=$'\E[0m'           # end mode
export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
export LESS_TERMCAP_so=$'\E[38;5;246m'    # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\E[0m'           # end underline
export LESS_TERMCAP_us=$'\E[04;38;5;146m' # begin underline

# Add extra paths to various utilities.
export PATH=$HOME/git/installs/android_sdk/tools:$PATH
export PATH=$HOME/git/installs/android_sdk/platform-tools:$PATH
export PATH=$DOTFILES_DIR/scripts:$PATH
export PATH=$HOME/.local/bin:$PATH

# Add extra man-page directory in .local.
export MANPATH=$HOME/.local/share/man:$MANPATH
