#!/usr/bin/env csh

if ( -x /usr/bin/dircolors ) then
    eval `env TERM=xterm SHELL=csh dircolors --csh`
    # Add default grep options
    alias ls 'ls --color=auto'
    alias dir 'dir --color=auto'
    alias vdir 'vdir --color=auto'
    alias grep 'grep --color=auto --exclude-dir={\.svn,\.git,\.repo}'
    alias fgrep 'fgrep --color=auto --exclude-dir={\.svn,\.git,\.repo}'
    alias egrep 'egrep --color=auto --exclude-dir={\.svn,\.git,\.repo}'
endif
