/* -*- ebnf-mode-style: ebnfx -*- */

symbol ::= expression |
           tmp


/* Comment */
rule_tmp ::= symbol |
             expression |
             test

// Second comment.
expression ::= ( A "|" B ) | ( A B ) |
               A* |
               A+ |
               C?

// Third Comment.
